name: github

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Cross-Platform build
        run: |
          make platfrom-build

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: anton-yurchenko/git-release@v3.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          CHANGELOG_FILE: "${GITHUB_WORKSPACE}/CHANGELOG.md"
        with:
          args: |
            .bin/*
